server:
  port: 8081

spring:
  application:
    name: ragnarok-antifraude
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/ragnarok_antifraude_db}
    username: postgres
    password: ${DB_PASS:postgre}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASS:}
      timeout: 100ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 4
          min-idle: 2

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always

antifraude:
  api-key: ${ANTIFRAUDE_API_KEY:}

logging:
  level:
    com.ragnarok.antifraude: INFO
